image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building.."
    - mvn $MAVEN_CLI_OPTS package -DskipTests

test:
  stage: test
  script:
    - echo "Testing.."
    - mvn $MAVEN_CLI_OPTS verify

sonar:
  stage: test
  except:
    - master
  before_script:
    - apt-get update -q
    - apt-get install -y jq
  script:
    - git fetch
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar -Dsonar.projectKey=com.trzewik:budget-tracker-server   -Dsonar.organization=mygitlab   -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=$SONAR_LOGIN   -Dsonar.branch.name=$CI_BUILD_REF_NAME
    - STATUS=$(curl -XGET -s https://sonarcloud.io/api/qualitygates/project_status\?projectKey\=com.trzewik:budget-tracker-server | jq -r .projectStatus.status);
      if [ $STATUS = "ERROR" ];
      then echo "Quality gate failed.";
      exit 1;
      else echo "Quality gate is OK.";
      fi;