spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:file:/${DB_URL}/budget-tracker-server/src/main/resources/data/budgettracker
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update